name = "NativeSVG"
uuid = "5f95e7b2-fe07-4078-b4a7-f744f426795c"
keywords = ["SVG"]
license = "MIT"
desc = "A pure Julia SVG generator."
authors = ["Ben Lauwens <ben.lauwens@gmail.com>"]
version = "0.1.0"

[deps]
Juno = "e5e0dc1b-0480-54bc-9374-aad01c23163d"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
